import React, { createContext, useContext, useState, useEffect } from 'react';
import { View, ActivityIndicator } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';


const T = {
    ro: {
        // Profile screen
        profileTitle: 'Profilul Meu',
        profileSub: 'Personalizează recomandările AI',
        profileSettings: 'Setări Aplicație',
        profileLangLabel: 'Limba',
        profileLangRo: 'Română',
        profileLangEn: 'Engleză',
        profileDarkMode: 'Mod Închis (Dark Mode)',
        profileDarkOn: 'Activat',
        profileDarkOff: 'Dezactivat',
        profileSkinType: 'Tipul de ten',
        profileSkinTypeSub: 'Selectează tipul tău de ten pentru recomandări personalizate de la CosmetiBot.',
        profileAllergies: 'Alergii și Sensibilități',
        profileAllergiesSub: 'Selectează ingredientele la care ești sensibilă. AI-ul va ține cont de ele în analiză.',
        profileSaveBtn: 'Salvează Profilul',
        profileSaved: 'Salvat!',
        profileSavedMsg: 'Profilul tău a fost actualizat cu succes.',
        profileErr: 'Eroare',
        profileSaveErr: 'Nu am putut salva profilul. Încearcă din nou.',
        profileDefaultUser: 'Utilizator',
        profileLoadingText: 'Se încarcă profilul...',
        profileLogoutTitle: 'Deconectare',
        profileLogoutMsg: 'Ești sigură că vrei să te deconectezi?',
        profileLogoutBtn: 'Deconectare',
        profileCancel: 'Anulează',
        profileYes: 'Da',
        // History
        historyTitle: 'Istoric Scanări',
        historySub: 'Dulăpiorul meu cu cosmetice',
        historyLoadingText: 'Încărcăm istoricul tău...',
        historyErrLoad: 'Nu am putut încărca istoricul',
        historyRetry: 'Încearcă din nou',
        historyEmpty: 'Încă nu ai scanat niciun produs.',
        historyEmptySub: 'Scanează o etichetă ca să apară în istoricul tău!',
        historyScannedAt: 'Ultima accesare',
        historyScanCount1: 'verificare',
        historyScanCountN: 'verificări',
        historyNoPhoto: 'Fără Poză',
        historyUnknownProduct: 'Produs Necunoscut',
        historyUnknownBrand: 'Brand Necunoscut',
        historyScore: 'Scor',
        // Chat
        chatSubtitle: 'Asistent AI Dermatologic',
        chatPlaceholder: 'Întreabă ceva...',
        chatYou: 'Tu',
        chatError: 'Scuze, am întâmpinat o eroare de conexiune cu serverul meu AI.',
        // Scanner
        scannerPermissionText: 'Avem nevoie de acces la cameră pentru a scana produse.',
        scannerAllow: 'Permite Accesul',
        scannerBack: 'Înapoi',
        scannerHome: 'Acasă',
        scannerProfile: 'Profil',
        scannerHistory: 'Istoric',
        scannerHint: 'Îndreaptă camera spre codul de bare',
        scannerRescan: 'Scanează din nou',
        scannerPickSource: 'Sursa Imagine',
        scannerPickSourceMsg: 'De unde vrei să selectezi poza?',
        scannerCamera: 'Camera',
        scannerGallery: 'Galerie',
        scannerCancel: 'Anulează',
        errorTitle: 'Eroare',
        errGalleryPerm: 'Avem nevoie de acces la galerie pentru a selecta o poză.',
        errorBoundaryTitle: 'Oops! Ceva nu a mers bine.',
        errorBoundaryMsg: 'A apărut o eroare neașteptată. Încearcă să reîncarci aplicația.',
        errorBoundaryBtn: 'Reîncearcă',
        // Product
        productLoading: 'Căutăm produsul în baza de date...',
        productNewTitle: 'Produs Nou Detectat!',
        productNewDesc: 'Acest produs nu a fost analizat inca.',
        productNewHint: 'Rezultatul va fi salvat automat și va fi disponibil instant pentru toți utilizatorii SmartSkin care vor scana același produs.',
        productNoPhoto: 'Fără poză',
        productUnknownName: 'Produs Necunoscut',
        productUnknownBrand: 'Brand Necunoscut',
        productChatPrompt: 'Ai întrebări despre cum afectează acest produs tenul tău?',
        productIngredientsTitle: 'Analiza Ingredientelor',
        productNoAnalysis: 'Analiza detaliată nu este disponibilă momentan.',
        productOfflineTitle: 'Fără Conexiune',
        productOfflineMsg: 'Nu am putut contacta serverul.\nAsigură-te că ești conectată la internet și încearcă din nou.',
        productTimeoutTitle: 'Analiză în Curs',
        productTimeoutMsg: 'Produsul este analizat pentru prima oară și durează puțin mai mult.\nApasă "Încearcă din nou" - va fi instant!',
        productOfflineBarcodeLabel: 'Cod produs:',
        productOfflineRetry: 'Încearcă din nou',
        productOfflineBack: 'Înapoi',
        productScanLabelBtn: 'Scanează Eticheta Ingredientelor',
        productBackToScanner: 'Înapoi la Scanner',
        productScoreLabel: 'Scor Siguranță',
        productPersonalAlerts: 'Alerte Personale',
        productWarnings: 'Avertismente',
        productIngredientSafe: 'Sigur',
        productIngredientLevel: 'Nivel',
        productScoreAdjustedPre: 'Scorul a fost ajustat de la ',
        productScoreAdjustedMid: ' la ',
        productScoreAdjustedPost: ' pe baza profilului tău.',
        productChatBtn: 'Întreabă CosmetiBot',
        // Login
        loginTitle: 'Bine ai revenit!',
        loginSub: 'Conectează-te la contul tău SmartSkin',
        loginEmailLabel: 'Email',
        loginPasswordLabel: 'Parola',
        loginBtn: 'Autentificare',
        loginGoogleBtn: 'Continuă cu Google',
        loginGoogleLoading: 'Se deschide Google...',
        loginGoogleErr: 'Nu am putut porni autentificarea Google.',
        loginGuest: 'Continuă ca Vizitator',
        loginBack: 'Înapoi la Scanare',
        scannerLogin: 'Autentificare',
        loginNoAccount: 'Nu ai cont? Înregistrează-te',
        loginErr: 'Eroare de autentificare',
        loginErrNoEmail: 'Te rugăm să introduci adresa de email.',
        loginErrInvalidEmail: 'Te rugăm să introduci o adresă de email validă.',
        loginErrNoPassword: 'Te rugăm să introduci parola.',
        loginErrNetwork: 'Nu am putut contacta serverul. Verifică conexiunea.',
        // Register
        registerTitle: 'Creează Cont',
        registerSub: 'Începe-ți călătoria spre o îngrijire sigură',
        registerNameLabel: 'Nume complet',
        registerNamePlaceholder: 'Maria Popescu',
        registerEmailLabel: 'Email',
        registerPasswordLabel: 'Parola',
        registerBtn: 'Înregistrare',
        registerHasAccount: 'Ai deja cont? Autentifică-te',
        registerErrNoName: 'Te rugăm să introduci numele complet.',
        registerErrInvalidEmail: 'Te rugăm să introduci o adresă de email validă.',
        registerErrPasswordShort: 'Parola trebuie să aibă cel puțin 6 caractere.',
        registerErrNetwork: 'Nu am putut contacta serverul. Verifică conexiunea.',
        registerErr: 'Eroare la înregistrare',
        registerSuccessTitle: 'Succes!',
        registerSuccessMsg: 'Contul a fost creat cu succes. Verifică-ți email-ul pentru confirmare.',
        // ManualAdd
        manualTitle: 'Adaugă Produs',
        manualSub: 'Ajută comunitatea adăugând acest produs. AI-ul nostru va citi pozele tale și va calcula scorul automat!',
        manualLoadingText: 'Inteligența Artificială Google Gemini extrage și analizează ingredientele din poză...',
        manualStep1: '1. Detalii',
        manualNameLabel: 'Nume Produs *',
        manualNamePlaceholder: 'ex: Aslavital Cremă Lift',
        manualBrandLabel: 'Brand (opțional)',
        manualBrandPlaceholder: 'ex: Farmec',
        manualStep2: '2. Ingrediente *',
        manualIngredientsDesc: 'Pentru a analiza toxicitatea, avem nevoie de o poză clară exclusiv cu secțiunea "Ingredients" (INCI) de pe spatele ambalajului.',
        manualRetakePhoto: 'Refă Poza',
        manualTakePhoto: 'Fotografiază Lista de Ingrediente',
        manualSubmitBtn: 'Adaugă în Baza de Date',
        manualCancelBtn: 'Anulează',
        manualErrNoName: 'Te rog să introduci numele produsului.',
        manualErrNoPhoto: 'Te rog să faci o poză la lista de ingrediente.',
        manualErrCamera: 'Avem nevoie de acces la cameră pentru a citi ingredientele.',
        manualErrImagePick: 'Eroare la selectarea imaginii.',
        manualErrTimeout: 'Analiza a durat prea mult (2 min). Încearcă o poză mai clară sau o conexiune mai bună.',
        manualErrGeneric: 'Nu am putut adăuga produsul.',
        manualSuccessTitle: 'Succes!',
        manualSuccessMsg: 'Produsul a fost citit de AI și salvat cu succes!',
        manualAddPhotoBtn: 'Adaugă Poza Etichetei',
        // Home
        homeGreetingMorning: 'Bună dimineața',
        homeGreetingAfternoon: 'Bună ziua',
        homeGreetingEvening: 'Bună seara',
        homeUserDefault: 'utilizator',
        homeBannerTitle: 'Știi ce pui\npe pielea ta?',
        homeBannerSub: 'Analizează orice cosmetică în câteva secunde cu baza de date CosIng a Uniunii Europene.',
        homeActionsTitle: 'Ce vrei să faci?',
        homeActionScanTitle: 'Scanează',
        homeActionScanSub: 'Citește codul de bare',
        homeActionSearchTitle: 'Caută',
        homeActionSearchSub: 'Găsește un produs',
        homeActionHistoryTitle: 'Istoric',
        homeActionHistorySub: 'Produsele tale',
        homeActionProfileTitle: 'Profilul Meu',
        homeActionProfileSub: 'Ten și alergii',
        homeInfoTitle: 'Cum funcționează SmartSkin?',
        homeInfoSub: 'Totul despre ingredientele din cosmeticele tale',
        homeInfoItem1Title: 'Baza de date CosIng UE',
        homeInfoItem1Desc: '30.000+ ingrediente INCI verificate de Comisia Europeană.',
        homeInfoItem2Title: 'AI Google Gemini',
        homeInfoItem2Desc: 'Scanează etichete cu camera și extrage ingredientele automat prin OCR.',
        homeInfoItem3Title: 'Analiză Personalizată',
        homeInfoItem3Desc: 'Rezultatele se adaptează la tipul tău de ten și alergiile declarate.',
        homeInfoItem4Title: 'CosmetiBot',
        homeInfoItem4Desc: 'Întreabă AI-ul orice despre produse, ingrediente sau îngrijire.',
        homeFooter: 'SmartSkin folosește datele oficiale CosIng ale Comisiei Europene pentru a evalua ingredientele cosmetice. Nu înlocuiește sfatul unui dermatolog.',
        // Profile skin types
        skinTypeNormal: 'Normală',
        skinTypeDry: 'Uscată',
        skinTypeOily: 'Grasă',
        skinTypeCombination: 'Mixtă',
        skinTypeSensitive: 'Sensibilă',
        // Allergies
        allergyParfum: 'Parfum / Fragrance',
        allergyParabens: 'Parabeni',
        allergySulfates: 'Sulfați (SLS/SLES)',
        allergyAlcohol: 'Alcool (Alcohol Denat.)',
        allergyDyes: 'Coloranți sintetici',
        allergyEssentialOils: 'Uleiuri esențiale',
        allergyLanolin: 'Lanolină',
        allergyFormaldehyde: 'Formaldehidă',
        allergyNickel: 'Nichel',
        allergyLatex: 'Latex',
        // Search
        searchTitle: 'Caută Produs',
        searchSubtitle: 'Cosmetice, creme, machiaj',
        searchPlaceholder: 'ex: Cerave, Garnier, foundation...',
        searchBadgeLegend: '= sursa rezultat',
        searchBadgeAnalyzed: 'Analizat',
        searchBadgeCosmetics: 'Cosmetice',
        searchBadgeMakeup: 'Machiaj',
        searchLoading: 'Căutăm în toate bazele de date...',
        searchError: 'Nu am putut efectua căutarea. Verifică conexiunea.',
        searchEmptyTitle: 'Caută orice produs cosmetic',
        searchEmptySub: 'Căutăm în produsele deja analizate de comunitate, în baza Open Beauty Facts și în Makeup API.',
        searchNoResultsSub: 'Încearcă alt nume de produs sau brand.\nDacă îl ai la tine, scanează eticheta direct!',
        searchResultsFound: 'rezultate găsite',
        searchNoBarcode: 'Fără cod',
        searchNeedsOcr: 'Necesită scanare',
        searchNoResultsFor: 'Niciun rezultat pentru',
        searchNoBarcodeTitle: 'Produs fără barcode',
        searchNoBarcodeMsg: 'Acest produs nu are un cod de bare asociat și nu poate fi analizat direct. Încearcă să îl scanezi fizic sau să îl adaugi manual.',
        // AnimatedScoreRing labels
        scoreLabelSafe: 'Sigur',
        scoreLabelModerate: 'Moderat',
        scoreLabelRisk: 'Risc Ridicat',
    },
    en: {
        // Profile screen
        profileTitle: 'My Profile',
        profileSub: 'Personalize AI recommendations',
        profileSettings: 'App Settings',
        profileLangLabel: 'Language',
        profileLangRo: 'Romanian',
        profileLangEn: 'English',
        profileDarkMode: 'Dark Mode',
        profileDarkOn: 'On',
        profileDarkOff: 'Off',
        profileSkinType: 'Skin type',
        profileSkinTypeSub: 'Select your skin type for personalized recommendations from CosmetiBot.',
        profileAllergies: 'Allergies & Sensitivities',
        profileAllergiesSub: 'Select ingredients you are sensitive to. The AI will consider them during analysis.',
        profileSaveBtn: 'Save Profile',
        profileSaved: 'Saved!',
        profileSavedMsg: 'Your profile has been updated successfully.',
        profileErr: 'Error',
        profileSaveErr: 'Could not save the profile. Please try again.',
        profileDefaultUser: 'User',
        profileLoadingText: 'Loading profile...',
        profileLogoutTitle: 'Log out',
        profileLogoutMsg: 'Are you sure you want to log out?',
        profileLogoutBtn: 'Log out',
        profileCancel: 'Cancel',
        profileYes: 'Yes',
        // History
        historyTitle: 'Scan History',
        historySub: 'My cosmetic cabinet',
        historyLoadingText: 'Loading your history...',
        historyErrLoad: 'Could not load history',
        historyRetry: 'Try again',
        historyEmpty: 'You have not scanned any product yet.',
        historyEmptySub: 'Scan a label to have it appear in your history!',
        historyScannedAt: 'Last accessed',
        historyScanCount1: 'check',
        historyScanCountN: 'checks',
        historyNoPhoto: 'No Photo',
        historyUnknownProduct: 'Unknown Product',
        historyUnknownBrand: 'Unknown Brand',
        historyScore: 'Score',
        // Chat
        chatSubtitle: 'AI Dermatology Assistant',
        chatPlaceholder: 'Ask something...',
        chatYou: 'You',
        chatError: 'Sorry, I encountered a connection error with my AI server.',
        // Scanner
        scannerPermissionText: 'We need camera access to scan products.',
        scannerAllow: 'Allow Access',
        scannerBack: 'Back',
        scannerHome: 'Home',
        scannerProfile: 'Profile',
        scannerHistory: 'History',
        scannerHint: 'Point the camera at the barcode',
        scannerRescan: 'Scan again',
        scannerPickSource: 'Image Source',
        scannerPickSourceMsg: 'Where do you want to pick the photo from?',
        scannerCamera: 'Camera',
        scannerGallery: 'Gallery',
        scannerCancel: 'Cancel',
        errorTitle: 'Error',
        errGalleryPerm: 'We need gallery access to select a photo.',
        errorBoundaryTitle: 'Oops! Something went wrong.',
        errorBoundaryMsg: 'An unexpected error occurred. Please try reloading the app.',
        errorBoundaryBtn: 'Try again',
        // Product
        productLoading: 'Searching for product in the database... \uD83C\uDF38',
        productNewTitle: 'New Product Detected!',
        productNewDesc: 'This product has not been analyzed yet.',
        productNewHint: 'The result will be saved automatically and instantly available to all SmartSkin users who scan the same product.',
        productNoPhoto: 'No photo',
        productUnknownName: 'Unknown Product',
        productUnknownBrand: 'Unknown Brand',
        productChatPrompt: 'Do you have questions about how this product affects your skin?',
        productIngredientsTitle: 'Ingredient Analysis',
        productNoAnalysis: 'Detailed analysis is not available at the moment.',
        productOfflineTitle: 'No Connection',
        productOfflineMsg: 'Could not reach the server.\nMake sure you are connected to the internet and try again.',
        productTimeoutTitle: 'Analysis in Progress',
        productTimeoutMsg: 'This product is being analyzed for the first time and it takes a little longer.\nPress "Try again" - it will be instant!',
        productOfflineBarcodeLabel: 'Product code:',
        productOfflineRetry: 'Try again',
        productOfflineBack: 'Back',
        productScanLabelBtn: 'Scan Ingredients Label',
        productBackToScanner: 'Back to Scanner',
        productScoreLabel: 'Safety Score',
        productPersonalAlerts: 'Personal Alerts',
        productWarnings: 'Warnings',
        productIngredientSafe: 'Safe',
        productIngredientLevel: 'Level',
        productScoreAdjustedPre: 'Score adjusted from ',
        productScoreAdjustedMid: ' to ',
        productScoreAdjustedPost: ' based on your profile.',
        productChatBtn: 'Ask CosmetiBot',
        // Login
        loginTitle: 'Welcome back!',
        loginSub: 'Sign in to your SmartSkin account',
        loginEmailLabel: 'Email',
        loginPasswordLabel: 'Password',
        loginBtn: 'Sign In',
        loginGoogleBtn: 'Continue with Google',
        loginGoogleLoading: 'Opening Google...',
        loginGoogleErr: 'Could not start Google authentication.',
        loginGuest: 'Continue as Guest',
        loginBack: 'Back to Scanner',
        scannerLogin: 'Sign In',
        loginNoAccount: 'No account? Register',
        loginErr: 'Authentication error',
        loginErrNoEmail: 'Please enter your email address.',
        loginErrInvalidEmail: 'Please enter a valid email address.',
        loginErrNoPassword: 'Please enter your password.',
        loginErrNetwork: 'Could not reach the server. Please check your connection.',
        // Register
        registerTitle: 'Create Account',
        registerSub: 'Start your journey to safe skincare',
        registerNameLabel: 'Full name',
        registerNamePlaceholder: 'Maria Popescu',
        registerEmailLabel: 'Email',
        registerPasswordLabel: 'Password',
        registerBtn: 'Register',
        registerHasAccount: 'Already have an account? Sign in',
        registerErrNoName: 'Please enter your full name.',
        registerErrInvalidEmail: 'Please enter a valid email address.',
        registerErrPasswordShort: 'Password must be at least 6 characters.',
        registerErrNetwork: 'Could not reach the server. Please check your connection.',
        registerErr: 'Registration error',
        registerSuccessTitle: 'Success!',
        registerSuccessMsg: 'Account created successfully. Please check your email for confirmation.',
        // ManualAdd
        manualTitle: 'Add Product',
        manualSub: 'Help the community by adding this product. Our AI will read your photo and calculate the score automatically!',
        manualLoadingText: 'Google Gemini AI is extracting and analyzing the ingredients from the photo...',
        manualStep1: '1. Details',
        manualNameLabel: 'Product Name *',
        manualNamePlaceholder: 'e.g. Cerave Hydrating Cleanser',
        manualBrandLabel: 'Brand (optional)',
        manualBrandPlaceholder: 'e.g. Cerave',
        manualStep2: '2. Ingredients *',
        manualIngredientsDesc: 'We need a clear photo of the "Ingredients" (INCI) section on the back of the packaging.',
        manualRetakePhoto: 'Retake Photo',
        manualTakePhoto: 'Photograph Ingredients List',
        manualSubmitBtn: 'Add to Database',
        manualCancelBtn: 'Cancel',
        manualErrNoName: 'Please enter the product name.',
        manualErrNoPhoto: 'Please take a photo of the ingredients list.',
        manualErrCamera: 'We need camera access to read the ingredients.',
        manualErrImagePick: 'Error selecting image.',
        manualErrTimeout: 'Analysis took too long (2 min). Try a clearer photo or a better connection.',
        manualErrGeneric: 'Could not add the product.',
        manualSuccessTitle: 'Success!',
        manualSuccessMsg: 'The product was read by AI and saved successfully!',
        manualAddPhotoBtn: 'Add Ingredients Photo',
        // Home
        homeGreetingMorning: 'Good morning',
        homeGreetingAfternoon: 'Good afternoon',
        homeGreetingEvening: 'Good evening',
        homeUserDefault: 'friend',
        homeBannerTitle: 'Do you know what\nyou put on your skin?',
        homeBannerSub: 'Analyze any cosmetic in seconds using the EU CosIng database.',
        homeActionsTitle: 'What do you want to do?',
        homeActionScanTitle: 'Scan',
        homeActionScanSub: 'Read barcode',
        homeActionSearchTitle: 'Search',
        homeActionSearchSub: 'Find a product',
        homeActionHistoryTitle: 'History',
        homeActionHistorySub: 'Your products',
        homeActionProfileTitle: 'My Profile',
        homeActionProfileSub: 'Skin & allergies',
        homeInfoTitle: 'How does SmartSkin work?',
        homeInfoSub: 'All about the ingredients in your cosmetics',
        homeInfoItem1Title: 'EU CosIng Database',
        homeInfoItem1Desc: '30,000+ INCI ingredients verified by the European Commission.',
        homeInfoItem2Title: 'Google Gemini AI',
        homeInfoItem2Desc: 'Scan labels with your camera and extract ingredients automatically via OCR.',
        homeInfoItem3Title: 'Personalized Analysis',
        homeInfoItem3Desc: 'Results adapt to your skin type and declared allergies.',
        homeInfoItem4Title: 'CosmetiBot',
        homeInfoItem4Desc: 'Ask the AI anything about products, ingredients or skincare.',
        homeFooter: 'SmartSkin uses official CosIng data from the European Commission to evaluate cosmetic ingredients. Not a substitute for dermatologist advice.',
        // Profile skin types
        skinTypeNormal: 'Normal',
        skinTypeDry: 'Dry',
        skinTypeOily: 'Oily',
        skinTypeCombination: 'Combination',
        skinTypeSensitive: 'Sensitive',
        // Allergies
        allergyParfum: 'Parfum / Fragrance',
        allergyParabens: 'Parabens',
        allergySulfates: 'Sulfates (SLS/SLES)',
        allergyAlcohol: 'Alcohol (Alcohol Denat.)',
        allergyDyes: 'Synthetic dyes',
        allergyEssentialOils: 'Essential oils',
        allergyLanolin: 'Lanolin',
        allergyFormaldehyde: 'Formaldehyde',
        allergyNickel: 'Nickel',
        allergyLatex: 'Latex',
        // Search
        searchTitle: 'Search Product',
        searchSubtitle: 'Cosmetics, creams, makeup',
        searchPlaceholder: 'e.g. Cerave, Garnier, foundation...',
        searchBadgeLegend: '= result source',
        searchBadgeAnalyzed: 'Analyzed',
        searchBadgeCosmetics: 'Cosmetics',
        searchBadgeMakeup: 'Makeup',
        searchLoading: 'Searching all databases...',
        searchError: 'Could not perform the search. Check your connection.',
        searchEmptyTitle: 'Search any cosmetic product',
        searchEmptySub: 'We search community-analyzed products, Open Beauty Facts and Makeup API.',
        searchNoResultsSub: 'Try a different product name or brand.\nIf you have it with you, scan the label directly!',
        searchResultsFound: 'results found',
        searchNoBarcode: 'No code',
        searchNeedsOcr: 'Needs scanning',
        searchNoResultsFor: 'No results for',
        searchNoBarcodeTitle: 'Product without barcode',
        searchNoBarcodeMsg: 'This product has no associated barcode and cannot be analyzed directly. Try scanning it physically or adding it manually.',
        // AnimatedScoreRing labels
        scoreLabelSafe: 'Safe',
        scoreLabelModerate: 'Moderate',
        scoreLabelRisk: 'High Risk',
    },
};

// ============================================================
// Color palettes
// ============================================================
export const LIGHT = {
    bg: '#FDFBF7',
    card: '#FFFFFF',
    header: '#FDFBF7',
    text: '#3C2A21',
    textSub: '#7A6256',
    textMuted: '#B0A39C',
    border: '#EAE4DE',
    inputBg: '#F5F2EA',
    inputText: '#3C2A21',
    placeholder: '#B0A39C',
    primary: '#8A5A44',
    primaryLight: '#F5EBE6',
    userBubble: '#8A5A44',
    aiBubble: '#FFFFFF',
    aiText: '#3C2A21',
    switchTrack: '#EAE4DE',
    switchThumb: '#FFFFFF',
    isDark: false,
};

export const DARK = {
    bg: '#1C1614',
    card: '#2A221E',
    header: '#1C1614',
    text: '#FDFBF7',
    textSub: '#D4C9C1',
    textMuted: '#8C7F78',
    border: '#3E322D',
    inputBg: '#3E322D',
    inputText: '#FDFBF7',
    placeholder: '#8C7F78',
    primary: '#D4A373',
    primaryLight: '#2A221E',
    userBubble: '#D4A373',
    aiBubble: '#2A221E',
    aiText: '#FDFBF7',
    switchTrack: '#3E322D',
    switchThumb: '#D4A373',
    isDark: true,
};

export const AppContext = createContext(null);

export function AppProvider({ children }) {
    const [lang, setLangState] = useState('ro');
    const [isDark, setIsDarkState] = useState(false);
    const [isGuest, setIsGuestState] = useState(false);
    const [ready, setReady] = useState(false);

    useEffect(() => {
        AsyncStorage.multiGet(['app_lang', 'app_dark', 'app_guest'])
            .then(([[, savedLang], [, savedDark], [, savedGuest]]) => {
                if (savedLang === 'ro' || savedLang === 'en') setLangState(savedLang);
                if (savedDark === 'true') setIsDarkState(true);
                if (savedGuest === 'true') setIsGuestState(true);
            })
            .catch(() => {})
            .finally(() => setReady(true));
    }, []);

    function t(key) {
        return T[lang]?.[key] ?? T.ro[key] ?? key;
    }

    function setLanguage(newLang) {
        setLangState(newLang);
        AsyncStorage.setItem('app_lang', newLang).catch(() => {});
    }

    function toggleDark() {
        const next = !isDark;
        setIsDarkState(next);
        AsyncStorage.setItem('app_dark', String(next)).catch(() => {});
    }

    function setIsGuest(val) {
        setIsGuestState(val);
        AsyncStorage.setItem('app_guest', String(val)).catch(() => {});
    }

    const colors = isDark ? DARK : LIGHT;

    if (!ready) return (
        <View style={{ flex: 1, backgroundColor: isDark ? '#1C1614' : '#FDFBF7', justifyContent: 'center', alignItems: 'center' }}>
            <ActivityIndicator size="large" color={isDark ? '#D4A373' : '#8A5A44'} />
        </View>
    );

    return (
        <AppContext.Provider value={{ lang, t, setLanguage, isDark, toggleDark, colors, isGuest, setIsGuest }}>
            {children}
        </AppContext.Provider>
    );
}

export function useApp() {
    const ctx = useContext(AppContext);
    if (!ctx) throw new Error('useApp must be used inside AppProvider');
    return ctx;
}
